Create Action not working as expected
praveenyr/cogniden pull request #5
Opened 2017-04-22 15:09 UTC by praveenyr

**Description:**  The _Create_ CRUD action flashes an error when I try to create a wiki through the app.The rspec tests work fine for the same though.

Test Coverage : 89.38%

2017-04-22 15:50 UTC, brittanyjspringer requested changes

2017-04-22 15:50 UTC, wonderwoman13 commented on app/controllers/wikis_controller.rb
> +    @wiki.user_id = params[:wiki][:user]
Change this to: 

@wiki.user_id = params[:wiki][:user] ||= current_user.id

That way, if the user ID is not sent, we set the user to the current user. This works and passes the tests.

2017-04-22 15:50 UTC, wonderwoman13 commented on spec/helpers/wikis_helper_spec.rb
> +require 'rails_helper'
Please delete any helper or view tests to keep the test runs clean :)

2017-04-22 15:50 UTC, wonderwoman13 commented
@praveenyr back to you! See comments above.

2017-04-22 17:27 UTC, praveenyr commented on app/controllers/wikis_controller.rb
> +    @wiki.user_id = params[:wiki][:user]
Cool,that worked.Thanks Brittany!

2017-04-24 21:02 UTC, brittanyjspringer approved these changes

2017-04-24 21:02 UTC, merged